-- CreateEnum
CREATE TYPE "ROLE" AS ENUM ('SUPPER_ADMIN', 'ADMIN', 'DOCTOR', 'PATIENT');

-- CreateEnum
CREATE TYPE "STATUS" AS ENUM ('BLOCKED', 'ACTIVE', 'DELETED');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "DeletedAt" TIMESTAMP(3),
ADD COLUMN     "isDeleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "needPasswordChange" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "role" "ROLE" NOT NULL DEFAULT 'PATIENT',
ADD COLUMN     "status" "STATUS" NOT NULL DEFAULT 'ACTIVE';
